
    ALTER USER dbauser IDENTIFIED BY dbauser ACCOUNT UNLOCK;
    ALTER USER dtv IDENTIFIED BY dtv ACCOUNT UNLOCK;
    ALTER USER training IDENTIFIED BY training ACCOUNT UNLOCK;
    ALTER USER repqueue IDENTIFIED BY repqueue ACCOUNT UNLOCK;
